[package]
name = "team_selector"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.16"
csv = "1.3.1"
serde = {version ="1.0.215", features = ["derive"]}
rayon = "1.10.0"
rand = "0.8.5"
